export interface Holding {
  ticker: string
  weight: number    // percentage
  name?:  string    // optional company name (populated from Yahoo Finance cache)
  rank?:  number
}

export interface ETFMeta {
  description: string
  holdings: Holding[]
}

export const ETF_META: Record<string, ETFMeta> = {
  // ── SPDR Sector ETFs ─────────────────────────────────────────────────────────
  XLK: {
    description: 'Technology Select Sector SPDR ETF',
    holdings: [
      { ticker: 'NVDA',  name: 'NVIDIA',            weight: 14.78 },
      { ticker: 'AAPL',  name: 'Apple',             weight: 12.14 },
      { ticker: 'MSFT',  name: 'Microsoft',         weight:  9.23 },
      { ticker: 'AVGO',  name: 'Broadcom',          weight:  6.03 },
      { ticker: 'MU',    name: 'Micron',            weight:  4.32 },
      { ticker: 'AMD',   name: 'AMD',               weight:  4.29 },
      { ticker: 'INTC',  name: 'Intel',             weight:  3.29 },
      { ticker: 'CSCO',  name: 'Cisco',             weight:  2.68 },
      { ticker: 'LRCX',  name: 'Lam Research',      weight:  2.39 },
      { ticker: 'PLTR',  name: 'Palantir',          weight:  2.36 },
    ],
  },
  XLV: {
    description: 'Health Care Select Sector SPDR ETF',
    holdings: [
      { ticker: 'LLY',   name: 'Eli Lilly',         weight: 13.20 },
      { ticker: 'UNH',   name: 'UnitedHealth',      weight:  9.80 },
      { ticker: 'JNJ',   name: 'J&J',               weight:  7.20 },
      { ticker: 'ABBV',  name: 'AbbVie',            weight:  6.90 },
      { ticker: 'MRK',   name: 'Merck',             weight:  5.10 },
      { ticker: 'TMO',   name: 'Thermo Fisher',     weight:  3.80 },
      { ticker: 'ABT',   name: 'Abbott',            weight:  3.50 },
      { ticker: 'ISRG',  name: 'Intuitive Surg',    weight:  3.20 },
      { ticker: 'DHR',   name: 'Danaher',           weight:  2.80 },
      { ticker: 'BMY',   name: 'Bristol-Myers',     weight:  2.50 },
    ],
  },
  XLF: {
    description: 'Financial Select Sector SPDR ETF',
    holdings: [
      { ticker: 'BRK/B', name: 'Berkshire B',       weight: 14.20 },
      { ticker: 'JPM',   name: 'JPMorgan',          weight: 12.80 },
      { ticker: 'V',     name: 'Visa',              weight:  8.50 },
      { ticker: 'MA',    name: 'Mastercard',        weight:  6.20 },
      { ticker: 'BAC',   name: 'Bank of America',   weight:  4.10 },
      { ticker: 'WFC',   name: 'Wells Fargo',       weight:  3.80 },
      { ticker: 'GS',    name: 'Goldman Sachs',     weight:  3.20 },
      { ticker: 'MS',    name: 'Morgan Stanley',    weight:  2.90 },
      { ticker: 'C',     name: 'Citigroup',         weight:  2.10 },
      { ticker: 'AXP',   name: 'Amex',              weight:  1.90 },
    ],
  },
  XLC: {
    description: 'Communication Services Select Sector SPDR ETF',
    holdings: [
      { ticker: 'META',  name: 'Meta',              weight: 23.40 },
      { ticker: 'GOOGL', name: 'Alphabet A',        weight: 12.50 },
      { ticker: 'GOOG',  name: 'Alphabet C',        weight: 11.80 },
      { ticker: 'NFLX',  name: 'Netflix',           weight:  5.60 },
      { ticker: 'TMUS',  name: 'T-Mobile',          weight:  4.10 },
      { ticker: 'VZ',    name: 'Verizon',           weight:  3.80 },
      { ticker: 'T',     name: 'AT&T',              weight:  3.50 },
      { ticker: 'CHTR',  name: 'Charter Comm',      weight:  3.20 },
      { ticker: 'EA',    name: 'EA Sports',         weight:  1.90 },
      { ticker: 'TTWO',  name: 'Take-Two',          weight:  1.80 },
    ],
  },
  XLY: {
    description: 'Consumer Discretionary Select Sector SPDR ETF',
    holdings: [
      { ticker: 'AMZN',  name: 'Amazon',            weight: 24.30 },
      { ticker: 'TSLA',  name: 'Tesla',             weight: 14.50 },
      { ticker: 'HD',    name: 'Home Depot',        weight:  8.90 },
      { ticker: 'MCD',   name: "McDonald's",        weight:  3.10 },
      { ticker: 'NKE',   name: 'Nike',              weight:  3.00 },
      { ticker: 'LOW',   name: "Lowe's",            weight:  2.80 },
      { ticker: 'BKNG',  name: 'Booking Holdings',  weight:  2.50 },
      { ticker: 'TJX',   name: 'TJX Companies',     weight:  2.30 },
      { ticker: 'SBUX',  name: 'Starbucks',         weight:  2.10 },
      { ticker: 'CMG',   name: 'Chipotle',          weight:  1.90 },
    ],
  },
  XLI: {
    description: 'Industrial Select Sector SPDR ETF',
    holdings: [
      { ticker: 'GE',    name: 'GE Aerospace',      weight:  5.80 },
      { ticker: 'CAT',   name: 'Caterpillar',       weight:  5.20 },
      { ticker: 'RTX',   name: 'RTX Corp',          weight:  4.90 },
      { ticker: 'HON',   name: 'Honeywell',         weight:  4.30 },
      { ticker: 'UPS',   name: 'UPS',               weight:  3.80 },
      { ticker: 'BA',    name: 'Boeing',            weight:  3.50 },
      { ticker: 'LMT',   name: 'Lockheed Martin',   weight:  3.20 },
      { ticker: 'DE',    name: 'Deere & Co',        weight:  3.00 },
      { ticker: 'MMM',   name: '3M',                weight:  2.50 },
      { ticker: 'WM',    name: 'Waste Management',  weight:  2.20 },
    ],
  },
  XLP: {
    description: 'Consumer Staples Select Sector SPDR ETF',
    holdings: [
      { ticker: 'COST',  name: 'Costco',            weight: 13.20 },
      { ticker: 'PG',    name: 'Procter & Gamble',  weight: 12.80 },
      { ticker: 'WMT',   name: 'Walmart',           weight: 11.50 },
      { ticker: 'KO',    name: 'Coca-Cola',         weight:  8.40 },
      { ticker: 'PEP',   name: 'PepsiCo',           weight:  7.90 },
      { ticker: 'PM',    name: 'Philip Morris',     weight:  5.20 },
      { ticker: 'MO',    name: 'Altria',            weight:  3.80 },
      { ticker: 'MDLZ',  name: 'Mondelez',          weight:  3.20 },
      { ticker: 'CL',    name: 'Colgate-Palmolive', weight:  2.90 },
      { ticker: 'KHC',   name: 'Kraft Heinz',       weight:  2.10 },
    ],
  },
  XLE: {
    description: 'Energy Select Sector SPDR ETF',
    holdings: [
      { ticker: 'XOM',   name: 'ExxonMobil',        weight: 22.50 },
      { ticker: 'CVX',   name: 'Chevron',           weight: 15.80 },
      { ticker: 'EOG',   name: 'EOG Resources',     weight:  4.80 },
      { ticker: 'SLB',   name: 'SLB',               weight:  4.20 },
      { ticker: 'MPC',   name: 'Marathon Petrol',   weight:  3.90 },
      { ticker: 'PSX',   name: 'Phillips 66',       weight:  3.50 },
      { ticker: 'VLO',   name: 'Valero Energy',     weight:  3.20 },
      { ticker: 'COP',   name: 'ConocoPhillips',    weight:  3.00 },
      { ticker: 'OXY',   name: 'Occidental',        weight:  2.80 },
      { ticker: 'KMI',   name: 'Kinder Morgan',     weight:  2.50 },
    ],
  },
  XLB: {
    description: 'Materials Select Sector SPDR ETF',
    holdings: [
      { ticker: 'LIN',   name: 'Linde',             weight: 14.50 },
      { ticker: 'SHW',   name: 'Sherwin-Williams',  weight:  6.80 },
      { ticker: 'FCX',   name: 'Freeport-McMoRan',  weight:  5.90 },
      { ticker: 'ECL',   name: 'Ecolab',            weight:  5.40 },
      { ticker: 'NEM',   name: 'Newmont',           weight:  4.80 },
      { ticker: 'APD',   name: 'Air Products',      weight:  4.20 },
      { ticker: 'NUE',   name: 'Nucor',             weight:  3.50 },
      { ticker: 'VMC',   name: 'Vulcan Materials',  weight:  3.20 },
      { ticker: 'MLM',   name: 'Martin Marietta',   weight:  3.00 },
      { ticker: 'ALB',   name: 'Albemarle',         weight:  2.80 },
    ],
  },
  XLU: {
    description: 'Utilities Select Sector SPDR ETF',
    holdings: [
      { ticker: 'NEE',   name: 'NextEra Energy',    weight: 14.80 },
      { ticker: 'SO',    name: 'Southern Co',       weight:  7.50 },
      { ticker: 'DUK',   name: 'Duke Energy',       weight:  7.10 },
      { ticker: 'AEP',   name: 'American Elec Pwr', weight:  4.90 },
      { ticker: 'SRE',   name: 'Sempra',            weight:  4.30 },
      { ticker: 'PCG',   name: 'PG&E',              weight:  3.80 },
      { ticker: 'D',     name: 'Dominion Energy',   weight:  3.50 },
      { ticker: 'EXC',   name: 'Exelon',            weight:  3.20 },
      { ticker: 'XEL',   name: 'Xcel Energy',       weight:  3.00 },
      { ticker: 'ED',    name: 'Con Edison',        weight:  2.50 },
    ],
  },
  XLRE: {
    description: 'Real Estate Select Sector SPDR ETF',
    holdings: [
      { ticker: 'PLD',   name: 'Prologis',          weight: 12.50 },
      { ticker: 'AMT',   name: 'American Tower',    weight:  8.90 },
      { ticker: 'EQIX',  name: 'Equinix',           weight:  7.80 },
      { ticker: 'WELL',  name: 'Welltower',         weight:  6.40 },
      { ticker: 'CCI',   name: 'Crown Castle',      weight:  5.90 },
      { ticker: 'PSA',   name: 'Public Storage',    weight:  5.20 },
      { ticker: 'O',     name: 'Realty Income',     weight:  4.80 },
      { ticker: 'DLR',   name: 'Digital Realty',    weight:  4.50 },
      { ticker: 'SPG',   name: 'Simon Property',    weight:  4.20 },
      { ticker: 'VICI',  name: 'VICI Properties',   weight:  3.80 },
    ],
  },

  // ── Industry / Sub-Sector ETFs ────────────────────────────────────────────────
  SMH: {
    description: 'VanEck Semiconductor ETF',
    holdings: [
      { ticker: 'NVDA',  name: 'NVIDIA',           weight: 20.85 },
      { ticker: 'TSM',   name: 'Taiwan Semi',       weight: 14.48 },
      { ticker: 'AVGO',  name: 'Broadcom',          weight:  8.08 },
      { ticker: 'INTC',  name: 'Intel',             weight:  4.68 },
      { ticker: 'AMD',   name: 'AMD',               weight:  4.55 },
      { ticker: 'MU',    name: 'Micron',            weight:  4.38 },
      { ticker: 'TXN',   name: 'Texas Instruments', weight:  4.19 },
      { ticker: 'KLAC',  name: 'KLA Corp',          weight:  3.26 },
      { ticker: 'ADI',   name: 'Analog Devices',    weight:  3.21 },
      { ticker: 'LRCX',  name: 'Lam Research',      weight:  2.90 },
    ],
  },
  HACK: {
    description: 'ETFMG Prime Cyber Security ETF',
    holdings: [
      { ticker: 'PANW',  name: 'Palo Alto Nets',    weight:  6.80 },
      { ticker: 'CRWD',  name: 'CrowdStrike',       weight:  6.50 },
      { ticker: 'FTNT',  name: 'Fortinet',          weight:  6.20 },
      { ticker: 'ZS',    name: 'Zscaler',           weight:  5.90 },
      { ticker: 'OKTA',  name: 'Okta',              weight:  4.80 },
      { ticker: 'CYBR',  name: 'CyberArk',          weight:  4.50 },
      { ticker: 'S',     name: 'SentinelOne',       weight:  3.90 },
      { ticker: 'VRNS',  name: 'Varonis',           weight:  3.50 },
      { ticker: 'TENB',  name: 'Tenable',           weight:  3.20 },
      { ticker: 'QLYS',  name: 'Qualys',            weight:  2.80 },
    ],
  },
  SKYY: {
    description: 'First Trust Cloud Computing ETF',
    holdings: [
      { ticker: 'IBM',   name: 'IBM',               weight:  5.80 },
      { ticker: 'AMZN',  name: 'Amazon',            weight:  5.20 },
      { ticker: 'GOOGL', name: 'Alphabet A',        weight:  5.10 },
      { ticker: 'MSFT',  name: 'Microsoft',         weight:  4.90 },
      { ticker: 'NET',   name: 'Cloudflare',        weight:  4.50 },
      { ticker: 'SNOW',  name: 'Snowflake',         weight:  4.20 },
      { ticker: 'DDOG',  name: 'Datadog',           weight:  3.80 },
      { ticker: 'CRM',   name: 'Salesforce',        weight:  3.50 },
      { ticker: 'NOW',   name: 'ServiceNow',        weight:  3.20 },
      { ticker: 'TWLO',  name: 'Twilio',            weight:  2.90 },
    ],
  },
  TAN: {
    description: 'Invesco Solar Energy ETF',
    holdings: [
      { ticker: 'ENPH',  name: 'Enphase',           weight: 12.50 },
      { ticker: 'FSLR',  name: 'First Solar',       weight:  8.50 },
      { ticker: 'RUN',   name: 'Sunrun',            weight:  6.90 },
      { ticker: 'CSIQ',  name: 'Canadian Solar',    weight:  5.20 },
      { ticker: 'ARRY',  name: 'Array Tech',        weight:  4.80 },
      { ticker: 'BE',    name: 'Bloom Energy',      weight:  3.50 },
      { ticker: 'SHLS',  name: 'Shoals Tech',       weight:  3.20 },
      { ticker: 'SPWR',  name: 'SunPower',          weight:  4.20 },
      { ticker: 'NOVA',  name: 'Sunnova',           weight:  3.80 },
      { ticker: 'SEDG',  name: 'SolarEdge',         weight:  7.80 },
    ],
  },
  JETS: {
    description: 'U.S. Global Jets ETF',
    holdings: [
      { ticker: 'DAL',   name: 'Delta Air Lines',   weight: 11.50 },
      { ticker: 'UAL',   name: 'United Airlines',   weight: 10.80 },
      { ticker: 'LUV',   name: 'Southwest',         weight:  9.20 },
      { ticker: 'AAL',   name: 'American Airlines', weight:  8.90 },
      { ticker: 'ALK',   name: 'Alaska Air',        weight:  7.50 },
      { ticker: 'JBLU',  name: 'JetBlue',           weight:  5.80 },
      { ticker: 'RYAAY', name: 'Ryanair',           weight:  4.50 },
      { ticker: 'SKYW',  name: 'SkyWest',           weight:  3.80 },
      { ticker: 'HA',    name: 'Hawaiian Airlines', weight:  3.50 },
      { ticker: 'MESA',  name: 'Mesa Air',          weight:  2.80 },
    ],
  },
  OIH: {
    description: 'VanEck Oil Services ETF',
    holdings: [
      { ticker: 'SLB',   name: 'SLB',               weight: 22.50 },
      { ticker: 'HAL',   name: 'Halliburton',        weight: 15.80 },
      { ticker: 'BKR',   name: 'Baker Hughes',       weight: 12.50 },
      { ticker: 'NOV',   name: 'NOV Inc',            weight:  5.80 },
      { ticker: 'LBRT',  name: 'Liberty Energy',     weight:  4.50 },
      { ticker: 'HP',    name: 'Helmerich & Payne',  weight:  3.80 },
      { ticker: 'WHD',   name: 'Cactus',             weight:  3.50 },
      { ticker: 'FTI',   name: 'TechnipFMC',         weight:  4.90 },
      { ticker: 'XPRO',  name: 'Expro Group',        weight:  2.50 },
      { ticker: 'PUMP',  name: 'ProPetro',           weight:  2.20 },
    ],
  },
  IYT: {
    description: 'iShares Transportation Average ETF',
    holdings: [
      { ticker: 'UPS',   name: 'UPS',               weight: 12.50 },
      { ticker: 'FDX',   name: 'FedEx',             weight: 11.80 },
      { ticker: 'ODFL',  name: 'Old Dominion',      weight:  8.90 },
      { ticker: 'CSX',   name: 'CSX',               weight:  7.50 },
      { ticker: 'NSC',   name: 'Norfolk Southern',  weight:  6.80 },
      { ticker: 'UNP',   name: 'Union Pacific',     weight:  6.20 },
      { ticker: 'JBHT',  name: 'J.B. Hunt',         weight:  5.50 },
      { ticker: 'DAL',   name: 'Delta Air Lines',   weight:  4.80 },
      { ticker: 'UAL',   name: 'United Airlines',   weight:  4.20 },
      { ticker: 'LUV',   name: 'Southwest',         weight:  3.80 },
    ],
  },
  EEM: {
    description: 'iShares MSCI Emerging Markets ETF',
    holdings: [
      { ticker: 'TSM',   name: 'Taiwan Semi',        weight:  8.90 },
      { ticker: 'BABA',  name: 'Alibaba',            weight:  4.20 },
      { ticker: 'TCEHY', name: 'Tencent',            weight:  4.00 },
      { ticker: 'SSNLF', name: 'Samsung',            weight:  3.80 },
      { ticker: 'INFY',  name: 'Infosys',            weight:  2.80 },
      { ticker: 'MELI',  name: 'MercadoLibre',       weight:  2.50 },
      { ticker: 'PDD',   name: 'PDD Holdings',       weight:  2.30 },
      { ticker: 'SE',    name: 'Sea Limited',        weight:  2.10 },
      { ticker: 'JD',    name: 'JD.com',             weight:  1.90 },
      { ticker: 'VALE',  name: 'Vale',               weight:  1.70 },
    ],
  },
  SOCL: {
    description: 'Global X Social Media ETF',
    holdings: [
      { ticker: 'META',  name: 'Meta',              weight: 12.50 },
      { ticker: 'SNAP',  name: 'Snap',              weight:  8.90 },
      { ticker: 'PINS',  name: 'Pinterest',         weight:  7.80 },
      { ticker: 'RDDT',  name: 'Reddit',            weight:  6.20 },
      { ticker: 'NTES',  name: 'NetEase',           weight:  5.20 },
      { ticker: 'BIDU',  name: 'Baidu',             weight:  4.80 },
      { ticker: 'SPOT',  name: 'Spotify',           weight:  4.20 },
      { ticker: 'MTCH',  name: 'Match Group',       weight:  3.80 },
      { ticker: 'BMBL',  name: 'Bumble',            weight:  3.20 },
      { ticker: 'ZG',    name: 'Zillow',            weight:  2.80 },
    ],
  },
  KCE: {
    description: 'SPDR S&P Capital Markets ETF',
    holdings: [
      { ticker: 'GS',    name: 'Goldman Sachs',     weight:  5.80 },
      { ticker: 'MS',    name: 'Morgan Stanley',    weight:  5.50 },
      { ticker: 'SCHW',  name: 'Schwab',            weight:  5.20 },
      { ticker: 'BLK',   name: 'BlackRock',         weight:  4.90 },
      { ticker: 'CME',   name: 'CME Group',         weight:  4.50 },
      { ticker: 'ICE',   name: 'Intercontinental',  weight:  4.20 },
      { ticker: 'CBOE',  name: 'Cboe Global',       weight:  3.80 },
      { ticker: 'MKTX',  name: 'MarketAxess',       weight:  3.50 },
      { ticker: 'LAZ',   name: 'Lazard',            weight:  3.20 },
      { ticker: 'EVR',   name: 'Evercore',          weight:  2.90 },
    ],
  },
  XLG: {
    description: 'Invesco S&P 500 Top 50 ETF',
    holdings: [
      { ticker: 'MSFT',  name: 'Microsoft',         weight: 11.80 },
      { ticker: 'AAPL',  name: 'Apple',             weight: 11.20 },
      { ticker: 'NVDA',  name: 'NVIDIA',            weight:  9.50 },
      { ticker: 'AMZN',  name: 'Amazon',            weight:  8.90 },
      { ticker: 'META',  name: 'Meta',              weight:  7.50 },
      { ticker: 'GOOGL', name: 'Alphabet A',        weight:  6.80 },
      { ticker: 'GOOG',  name: 'Alphabet C',        weight:  6.20 },
      { ticker: 'TSLA',  name: 'Tesla',             weight:  4.50 },
      { ticker: 'BRK/B', name: 'Berkshire B',       weight:  3.80 },
      { ticker: 'AVGO',  name: 'Broadcom',          weight:  3.20 },
    ],
  },
  XRT: {
    description: 'SPDR S&P Retail ETF',
    holdings: [
      { ticker: 'AZO',   name: 'AutoZone',          weight:  2.50 },
      { ticker: 'ORLY',  name: "O'Reilly Auto",     weight:  2.40 },
      { ticker: 'CASY',  name: 'Casey\'s General',  weight:  2.30 },
      { ticker: 'W',     name: 'Wayfair',           weight:  2.20 },
      { ticker: 'M',     name: 'Macy\'s',           weight:  2.10 },
      { ticker: 'GME',   name: 'GameStop',          weight:  2.00 },
      { ticker: 'BOOT',  name: 'Boot Barn',         weight:  1.90 },
      { ticker: 'ULTA',  name: 'Ulta Beauty',       weight:  1.80 },
      { ticker: 'FIVE',  name: 'Five Below',        weight:  1.70 },
      { ticker: 'CVNA',  name: 'Carvana',           weight:  1.60 },
    ],
  },
  OEF: {
    description: 'iShares S&P 100 ETF',
    holdings: [
      { ticker: 'MSFT',  name: 'Microsoft',         weight: 12.50 },
      { ticker: 'AAPL',  name: 'Apple',             weight: 11.80 },
      { ticker: 'NVDA',  name: 'NVIDIA',            weight:  9.20 },
      { ticker: 'AMZN',  name: 'Amazon',            weight:  8.90 },
      { ticker: 'META',  name: 'Meta',              weight:  7.80 },
      { ticker: 'GOOGL', name: 'Alphabet A',        weight:  6.50 },
      { ticker: 'GOOG',  name: 'Alphabet C',        weight:  6.00 },
      { ticker: 'BRK/B', name: 'Berkshire B',       weight:  3.80 },
      { ticker: 'TSLA',  name: 'Tesla',             weight:  3.50 },
      { ticker: 'AVGO',  name: 'Broadcom',          weight:  3.20 },
    ],
  },
}
